### ISSUE TITLE
search queries aren't recognizing special chars

### ISSUE THREAD

**Issue by bdionne** [protegeproject/lucene-search-tab#1]
![screen shot 2016-08-30 at 2 44 53 pm](https://cloud.githubusercontent.com/assets/31741/18102375/6007ddd0-6ec0-11e6-9127-178c4887e27f.png)

**Comment by johardi** [comment]
Is there a particular need for that kind of search keyword?

**Comment by bdionne** [comment]
Yes, in real-world terminologies there are often very quite complex terms and formulas

![image](https://cloud.githubusercontent.com/assets/31741/18123675/effab2ec-6f3c-11e6-8117-b7ae731a60c7.png)
