### ISSUE TITLE
ontology indexed multiple times

### ISSUE THREAD

**Issue by bdionne** [protegeproject/lucene-search-tab#2]
Logging out and in to the protege client, and opening the same ontology, causes it to be fully indexed each time. I noticed this when logging out to login as admin and change the metaproject options.

If you exit the app entirely and bring it back up, this re-indexing does not occur.

**Comment by johardi** [comment]
Could you confirm that the index directory was created when the search tab performed the indexing for the first time? And the directory was still present when you logged out and logged in. To see the index directory location, look at the Lucene Search tab in the Preferences dialog.

**Comment by bdionne** [comment]
Yes it appear so. What's interesting is that when you close and reopen the app, it does _not_ index. But if you then logout and login it starts doing it again.

**Comment by bdionne** [comment]
@josef - per our discussion there seems to be three issues here:
1. The search tab manager is registering for both ontology changes events and active ontology changed events. It's getting the former first and processing them before it knows which index to use
2. The first full indexing doesn't occur until the user does a query. It should probably do it the first time it's opened
3. It should not index the snapshot and changes from the server every time it's opened, but rather once, as in 2 above

I'm wondering if this might clear up the other issue we see also. That would be sweet

**Comment by rsgoncalves** [comment]
This repo is just for the Lucene UI. The issue should be in https://github.com/protegeproject/lucene-search-plugin

**Comment by bdionne** [comment]
? - well the [code](https://github.com/protegeproject/lucene-search-tab/blob/master/src/main/java/edu/stanford/protege/search/lucene/tab/engine/SearchTabManager.java#L86) we're discussing is in this repo

I can open a ticket there if you wish

**Comment by rsgoncalves** [comment]
Hmm that code shouldn't be here then, we'll figure it out.

**Comment by johardi** [comment]
This is a very non-trivial bug that I have to trace down into protege-client code that deals with opening ontologies from the server. To have the fix please update the code for lucene-search-plugin, lucene-search-tab and protege-client, and remove any existing index directories in the preferences prior this fix.

**Comment by bdionne** [comment]
nice digging @johardi - I'd like to understand this change better, particularly the one in protege-client, before I incorporate into the protege-client, especially since it touches 3 repos.

the change from yesterday seemed to fix the re-indexing problem

**Comment by bdionne** [comment]
This is [still](https://github.com/bdionne/lucene-search-tab/issues/4) not quite working (reportedly, haven't reproduced it yet)

@johardi - when you did this second fix, involving the mock ontology, did you by chance test it with a large ontology? I looked this over and it seemed ok, but it had the same effect as the use of the `SessionRecorder` to stop history recording. In other words, creating a mock ontology still results in all those events being generated there's just no one registered to receive them. 

I haven't had a chance to test this, my main concern was the copying of the full ontology and the effect with a large ontology.

We're also seeing interactions between the editor and the incremental indexer, and I 'm wondering if it would be better to let the `SessionRecorder` drive the indexing, after committing. This way the indexer would work unnecessarily when users make edits and then cancel them.

**Comment by johardi** [comment]
I've tested it using the NCI Thesaurus (160328). Did you update all the three modules (i.e., lucene-search-plugin, lucene-search-tab and protege-client)?

**Comment by bdionne** [comment]
Not yet, as I mentioned above, I haven't had a chance to test this. It was a little late to be merging branches from three repos right before a release, given they've diverged some, I didn't want to break anything.

So the copy ontology didn't double the memory consumption while in progress?
